LARGER_FENETRE=1920
HAUTEUR_FENETRE=1080
FULLSCREEN=False
SIZE_BLOCK=64
FONT="./assets/fonts/ka1.ttf"
TEXT_COLOR=(255,255,255)
ACCOUNT_LOCATION="./config/accounts/"
REWARD_VALEUR={"dirt" : 1, "grass_block" : 1, "stairs" : 0, "stone": 2}
BLOCK_LIST=["dirt", "grass_block", "stairs", "stone"]